---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prysm
  namespace: observability
spec:
  staticConfigs:
    - labels:
        job: prysm
      targets:
        - 192.168.0.151:8080
        - 192.168.0.151:8081
  metricsPath: /metrics
