---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredResources
metadata:
  name: pod-must-have-resource-constraints
spec:
  match:
    labelSelector:
      matchExpressions:
        - key: gatekeeper.sh/exempt
          operator: NotIn
          values: ["true"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
  parameters:
    requests:
      - cpu
      - memory
