apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPCapabilities
metadata:
  name: restrict-capabilities
spec:
  match:
    labelSelector:
      matchExpressions:
        - key: gatekeeper.sh/exempt
          operator: NotIn
          values: ["true"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
  parameters:
    allowedCapabilities: []
    requiredDropCapabilities: ["ALL"]
