---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPRunAsNonRoot
metadata:
  name: run-as-non-root
spec:
  match:
    labelSelector:
      matchExpressions:
        - key: gatekeeper.sh/exempt
          operator: NotIn
          values: ["true"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
