---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: flux-system
spec:
  targetNamespace: gitea
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/turing/gitea/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
