---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/ks.yaml
  - flaresolverr/ks.yaml
  - jellyseerr/ks.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sonarr/ks.yaml
