apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:YJdS8JIMlTMr,iv:miXJ930wLBz5kxchg23HjTCEWwOxxzeJm8/hPiQxexQ=,tag:9q6Vm6M6V3YDAyzNiXcw2g==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:mo9fbom/KzjC,iv:2fvOhZkSjg1REvdYt2VsFAm8yJPgAThWWa1xq8EC3q4=,tag:45U92kwAIfiQP7Z5lJn22Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:mqZMP3iqodFwe8Xnk0EZf4bgTqE4dX+/gC+9MYeB7gy11f/2cVEKAv6GACc=,iv:osUmNNDJYw7+DRibudGnZkdEJo9aSgYwNPHZjJzR3nw=,tag:KBlYdhI+pGP6xDYfYT5cvQ==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ1QrV2dYaFYwV0pWQVRB
            b3VLcTgvV2x2VVppdWV2Y1EvbUs5d3h2YW0wCjhyZGFZNm84N3UwQmhVTXZ4Vms4
            Sk1NNW9Pajgyb0VNdTBuYmpkUVNwaGsKLS0tIEZrbktZZ2pHRzdjOVNVYU5kRURQ
            bVBxWC91ZVBpOVFpSWJySjVHY2NycGcK8Az5knC2FOtJJtfJJO5+o4z8TRrEbfXc
            r7uE9ZZX03Z9pI6lbjArYa+/I52UXPvFi8iLvCiCug7XsPg+hHg4DA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQS9yUTVXazRHS1NDWkxh
            d3FkM1loc3BteWFtOHk2TVgzNGk2L1g0K21NCkY2VkVNYUttWHc0b3BiUk1UaU00
            Uk1rT21Nbnk5am91VVhtYk9yRW9PWFkKLS0tIGlKZFJKNTNnd0N5YzhIajYrSFB0
            NDJuZXJTVFZzOGVtQi9JT2xUajVUcjQKKNrmt9rJgfkGQVyUuefIYWHKvtecUp15
            rXL5J/8QA94K0RN3FtE+qZAHWAml+M+3lBtrWslbWNkRF6lgGqkziw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T20:46:22Z"
    mac: ENC[AES256_GCM,data:eHfiaCmy3YxR0I62tsbXTcFvn/i6BbCIgjpno2+zjzQQnSyC8nii0T8uo00shfgibDlxTzbPy6nLJZZEg33LDfzbP1by5OW3M4g/3yDyn8qKxyPOK3+ZKCBm42WsVwNMgT8VW5I18DqHLoXgzixu2GfHgTm4KRpOtuTeh3WMpy0=,iv:EExYn9jVFHOT5CcCH/vqqelAjSRqdtsBvGoVbandHWI=,tag:8ZRpnVrRRHhW3rcoPSNwIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
