apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: gitea-runner-secret
    namespace: gitea
stringData:
    GITEA_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:VFNfdgiDbmzzxl6FRa4cYIfD2cqmdwNY/GHIzTDRTFk4PWY0bZahcQ==,iv:71/YNZHyGW3hDA4OSE2/RjGulr/LWePUyK/eT0gINQo=,tag:SKarqRgcsFs0P3VYT9F1JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2E4UERYYlkrZSsxWm1O
            MThKVmtFRllpcWhkem9RamQ3clhPUGJyTmxzCk43a3kwMzlCbEFsN3AyeTdzUCtO
            cDhBRlV0dFAwMmhDNjZZeTd3RHQ2WUkKLS0tIFVWSTZXRFZaTG5veDVtaDRXRWFm
            ZGE5anVSUDI5WUlPSndXV0k2Q09BRVkKfR1dtdONPLIK7DiLZaGGP+Lb6dISDS5Q
            JDl8OrWkgSDc4ob2nA/Qut/9ICwdGyp2lHzU2WigAe04r14HbW6Kkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZFpJaHlBNHVCYlExUlFP
            a3REb0JoUlYvLzBIRm1zU1Ywc2s4Nm5NNVFrCmtEZVhmWVhVeGFNUVNXcy9XV09h
            QUFvd0pXdnBhMXZxcWJISzZFVGZueEUKLS0tIDgzdXR3U1l5YjBvZ0d6Y3NWRldm
            TmRPYVIvc3N1d3hQaGdvNWhycEx3TE0KEBVv8wussL+9EC2SvsiqdA7+F23gGbzd
            EFKA3YBaMMV5iPBHEfM0zdjed/t/qasB7SWjxxSXksaZldXb0gZRGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T13:39:23Z"
    mac: ENC[AES256_GCM,data:apnLbIAhsUD4tCs3r3H2DQKSS6X0XTzcvydQ3d7ZVYC/mQbFYGDS9KkyS89FMPZcH6zll+yzNJGkm1D/4JjV2Zebm0cCl1F/R9XytVGAjETJ8fa1KA/8fzGGoqjyuobsKe+ycYxxLMxFQRSRU2j0vS7kxdaeD2PhVTPJBWm0670=,iv:aKzAl6+7AYEVMXnO4GfcC7NAjJF7wKl8KZf/dmnrS7w=,tag:Ke7jkPwdEl1YVuS5C8rhXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
