apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
    namespace: storage
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:8Qt7k7yEx0N/407QpXmK4L1yo+xB3VQ/gjCZJUQli8M=,iv:wARCGaP2GPPNeGRA21ijqLsmoVeDRf/UwBHczAhiyp8=,tag:w04tH5jR0CwTvpw4JWxmzw==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbXFQMklhcE5VUXpLb2VZ
            RU9EenJ0eWhnajZsVUgyNHdCZEd1Y1ZSUzJFCnpHbGlhcU96SUdkaWxKZ0Z0bDdj
            KzZqQyswUm15OS9rT2xNeVo5TlBWdGcKLS0tIFVlQ3FkU2RSM2hzSUh1ZDJ5R1RK
            Z2I5Um5ZZ1pnSFJCcnUzeFJGT2E3alEKlxRSgYC9uPxIf7N0IzityP6S00N9uvqQ
            aLz43mwN57b7XunneHkrg3MWHsKw/+mFIhoou4GPojUk29Zlyf5O0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQSt3bERiVWxFTExvS3Rq
            bkZSZDdlcC9vaXpCT3d2WVdnK3k3RE1nSVR3CkJBQmowcVVWM0F6ZVVua1BPUGZ3
            LzJyeFBKRkpUeU53MjZNMzdPWGRtWVUKLS0tIHVJTk1zZ2dBVnluRHVuTFArM1FY
            SmRaS3JRaGRRbmtvRENFTkJNd2lwYm8K75vdTZ4Tkhd0UcMrlPZDq5imtissackh
            eRliV7nn7845FIdlTaCY5ETx8y5pfsvpr7xwz8BDIOkIJuqox9scEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T21:24:21Z"
    mac: ENC[AES256_GCM,data:w+gqt0EV3I32pj2iV+svqb0qOaM7/w4G0C0hmOzup4P1f6J8uAnRMOZNvo+63FU0MbrK51GAO4J6vIRR2Hf0RL22dZynuHsjxyBoxbZzOGDTGtx1mFOQcJ6PRva3C9TU1QjXkxnAYgGm84X4l7tBL3rPL003CKNUI5qJzHqrhEI=,iv:QXr6Fdmm4qtmU7f3Y7uwFcJ3OUQx+OM86gwqntuyo14=,tag:g8cwkrFOnFXUvQ/g1K33gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
