apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: booklore-secret
    namespace: media
stringData:
    DATABASE_USERNAME: ENC[AES256_GCM,data:w8U5V3Omf/g=,iv:0W45QMF3Uwr0IvLcaAp64iAmBGB5y4gyi7gSzlJ7zek=,tag:dI2gPosSL5RrjqIYLANkqw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:SLsw5SEp/zbbsl+6aSbC6kfRetUUzvFftWc0S8+UGlg=,iv:r98qk2JjNPNSstAqDXlTP2FUvtZzRUQF5xxA7A/410o=,tag:GHqXrg3KHgO9cyklE4aaJQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:EGQ5YYt3DTmQXxeCIHjvh+IBsVdGd69tNIOuLUIJcms=,iv:rpcoO+eORY8iJGv2RAA3bJ6Sg3DFxZKu0OmwZdVJLuE=,tag:NtyS2BxN7UraksfDxKPPFQ==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWG9UaGs3UE5NRjBKTTBa
            SmVHV0cwUUxtdmJ1bGFHNFZBYUhWMVdlRncwCjQwKzRRbGVEaFBOemlwMm95QmtM
            OFpsMjltcDNuQXRQN0d4RFRJQS9uaWMKLS0tIEVac1hlQStML3dZcTVUZ2hFTGdk
            V1o3VjFvTThUaGpHdUFRRmdkMkExYzAKriLh5eVJJANuwZLeEFjqSeWJ53IgRjkh
            NwyVOiGqGWsH3pG4N6ds6pWOxBLtUJRLB1ku0W9BImeI7J+2+ZptMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa0l4a0w5QVNtYzk5UWt1
            ZmRnano2Z3VzZTNvcmdaRXF1RkV0c3dPMjF3ClA2TVdNNGVLcjlkQ0hEYVppd1ZJ
            U0dGbWJNYnNhcVdQZzdFbENxdEYzYWMKLS0tIHdMSzJ0VldZYlZnZmZ3RmRTZlgv
            ZlNZQmVuUjZiMmNBT0kzQlpRbTNTVHMK01VwStA73fKR1rgpaxwAF8Y3LTwQxB/M
            fa0mkCo+Hem6YaaxN24Vd5hHXJG/gPMnfyx5gTsDTg6OCaXVKwOKvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T15:46:17Z"
    mac: ENC[AES256_GCM,data:3Oup7KloJbd+n9NXbMC/mina/MgG5RuwsApU7bcLKKOfvVqtaDQy6xskGBoFlskmm9Ofz9YCVJGSTIP6j6IYvxRDsmRCAU/ocPihBx7hbFU4LxUsgVb14wKmM4mjv6x0jLKjsw0O1cAc8diWxHeIVEFuDZdlxXOWpY1jv9+J/6c=,iv:QpUUNw6zy0IgXNW3qM3DBqUI6zhwU4qmqbDE2t90kXQ=,tag:uQPx4mhFU6HDa0e7oPcOPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
